version: v1.0
name: Initial Pipeline
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: "🚀 Deploy"
    jobs:
      - name: deploy
        commands:
          - echo "DEPLOYING..."